# Generated by Django 3.2 on 2021-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_alter_moviepost_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmovie',
            name='time',
            field=models.ManyToManyField(blank=True, to='movie.ShowTime'),
        ),
    ]
