# Generated by Django 3.2.3 on 2021-05-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_bookmovie_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('booked_seats', models.ManyToManyField(blank=True, to='movie.Seat')),
                ('time', models.ManyToManyField(blank=True, to='movie.ShowTime')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviepost')),
            ],
        ),
        migrations.DeleteModel(
            name='bookmovie',
        ),
    ]
