# Generated by Django 3.2.3 on 2021-05-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
